### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/kda#11]
Create an initial release.

Put it on PyPi and let ReadTheDocs generate your initial docs #10 

I strongly recommend using [semantic versioning](https://semver.org). Use a CHANGES or CHANGELOG file.

**Comment by nawtrey** [comment]
Closing, initial release was created a while back (i.e. [4b77c84](https://github.com/Becksteinlab/kda/commit/4b77c84c5794e888aee37b74d2cbe03e04b8d1d3)).
