### ISSUE TITLE
Move testing suite from Travis-CI to GitHub Actions

### ISSUE THREAD

**Issue by nawtrey** [Becksteinlab/kda#18]
Travis CI has changed their testing platform to only allow 1000 minutes of testing time per month for free users, which may become intractable once the testing suite is fully developed. 

Can view a guide for the migration [here](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions).

**Comment by orbeckst** [comment]
This is now urgent because we ran out of free Travis credits and CI stopped.

**Comment by nawtrey** [comment]
Yes, I'll get this migrated to GitHub Actions ASAP.

**Comment by nawtrey** [comment]
Closed via #35.

**Comment by orbeckst** [comment]
Good work!
