### ISSUE TITLE
Fix Travis package imports so tests can run

### ISSUE THREAD

**Issue by nawtrey** [Becksteinlab/kda#5]
test_KDA.py keeps failing on Travis because it cannot import the packages properly. Make these package imports explicit (should be aware of package dependencies) and verify Travis is importing them correctly. Package import must be explicitly listed in both setup.py and Travis.yml.

**Comment by orbeckst** [comment]
Is this still an issue? Tests seem to be running. Can this be closed?

**Comment by nawtrey** [comment]
Yes it can! Closing now.
