### ISSUE TITLE
Add analysis examples

### ISSUE THREAD

**Issue by nawtrey** [Becksteinlab/kda#6]
Since there are already a host of examples worked out with solutions it would be prudent to throw these all into some sort of documentation where the code can be made available for others to tailor to their specific needs.

**Comment by orbeckst** [comment]
There is a way to include Jupyter notebooks in sphinx documentation. For instance, the MDAnalysi [User Guide](https://userguide.mdanalysis.org/) uses this extensively.

**Comment by nawtrey** [comment]
I think this can be closed now that the [kda-examples](https://github.com/Becksteinlab/kda-examples) has been created.
